verify the settings are correct before running

diff --git a/.github/workflows/refresh.yaml b/.github/workflows/refresh.yaml
--- a/.github/workflows/refresh.yaml
+++ b/.github/workflows/refresh.yaml
@@ -1,8 +1,8 @@
 name: Refresh
 on:
-  # performed every two hours, disabled by default, uncomment and modify as needed
-  # schedule:
-  #   - cron: "0 */2 * * *"
+  # performed every two hours
+  schedule:
+    - cron: "0 */2 * * *"
   workflow_dispatch:
 
 env:
@@ -34,6 +34,24 @@ jobs:
 
       - name: Install
         run: pip3 install -r requirements.txt
+
+      - name: Check
+        run: |
+          if [ -z "$GIST_PAT" ]; then
+              echo "Error: environment 'GIST_PAT' cannot be empty"
+              exit 1
+          fi
+
+          if [ -z "$GIST_LINK" ]; then
+              echo "Error: environment 'GIST_LINK' cannot be empty"
+              exit 1
+          fi
+
+          LINK_PARTS=$(echo "$GIST_LINK" | awk -F'/' 'NF==2 && $1!="" && $2!=""')
+          if [ -z "$LINK_PARTS" ]; then
+              echo "Error: environment 'GIST_LINK' is not valid, should be 'username/gist_id' format"
+              exit 1
+          fi
 
       - name: Refresh
         run: python -u subscribe/collect.py --all --clean --overwrite --skip
